# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_poliza'),
        ('users', '0002_auto_20160807_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Poliza'),
        ),
    ]
