# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 21:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medidores', '0001_initial'),
        ('empresas', '0002_poliza'),
        ('users', '0003_user_poliza'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medidores.Medidor')),
            ],
        ),
        migrations.CreateModel(
            name='PolizaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Poliza')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='medidor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='poliza',
        ),
        migrations.AddField(
            model_name='polizauser',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medidoruser',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
