# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Poliza_Acueducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acueducto', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Acueducto')),
                ('poliza', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polizas.Poliza')),
            ],
            options={
                'verbose_name': 'P\xf3liza vs Acueducto',
                'verbose_name_plural': 'P\xf3lizas vs Acueductos',
            },
        ),
        migrations.CreateModel(
            name='Poliza_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Cliente')),
                ('poliza', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polizas.Poliza')),
            ],
            options={
                'verbose_name': 'P\xf3liza vs Cliente',
                'verbose_name_plural': 'P\xf3lizas vs Clientes',
            },
        ),
    ]
