# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('izarnet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Izarnetv1',
            new_name='Izarnet',
        ),
        migrations.RenameModel(
            old_name='Izarnetv1Procesados',
            new_name='IzarnetProcesados',
        ),
        migrations.AlterModelOptions(
            name='izarnet',
            options={'verbose_name': 'Izarnet', 'verbose_name_plural': 'Izarnet'},
        ),
        migrations.AlterModelOptions(
            name='izarnetprocesados',
            options={'verbose_name': 'Archivos Procesados', 'verbose_name_plural': 'Archivos Procesados'},
        ),
    ]
