# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-20 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izarnetv1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izarnetv1',
            name='caudal',
            field=models.FloatField(default=None, verbose_name='Caudal Promedio'),
        ),
    ]
