# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izarnetv1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Izarnetv1Procesados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
    ]
